### ISSUE TITLE
kotlin.UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by amit-affirm** [plaid/plaid-link-android#105]
# The problem
Seeing this crash occasionally

```
Caused by kotlin.UninitializedPropertyAccessException
lateinit property component has not been initialized
com.plaid.link.Plaid.getComponent$link_sdk_web_release (Plaid.java:1)
com.plaid.link.internal.LinkActivity.onCreate (LinkActivity.java:2)
```

# Environment
com.plaid.link:sdk-core:2.0.0

|                        |  |
| ------------------------| ---------- |
| Android OS Version                    | 9, 10                |
| Android Devices/Emulators    |  Galaxy S8               |

# Steps to Reproduce

Not sure

# Expected Result
No crash

<img width="314" alt="Screen Shot 2020-10-19 at 11 17 04 AM" src="https://user-images.githubusercontent.com/56614068/96495484-c9ccb900-11fc-11eb-96fa-43ebb63d7848.png">

**Comment by amytang0** [comment]
Hi, can you try upgrading to our latest SDK 3.1.0?

**Comment by patrickomatic** [comment]
Hi - @amytang0 

We've been running into this issue consistently on a `Lenovo Tab M10 FHD Plus Android 9 (SDK 28)` but it works for someone else here on Android 11.  The issue happens when doing the OAuth flow with Chase then at the end when it transfers the user back to our app we get this crash rather than our app opening.  Here's the stack trace we've captured:

```
kotlin.UninitializedPropertyAccessException: 
  at com.plaid.link.internal.BasePlaid$Companion.getINSTANCE (SourceFile:1)
  at com.plaid.internal.redirect.LinkRedirectDependencyFragment.a (SourceFile:23)
  at com.plaid.internal.core.ribs.android.DependencyFragment.onActivityCreated (SourceFile:5)
  at androidx.fragment.app.Fragment.performActivityCreated (Fragment.java:2717)
  at androidx.fragment.app.FragmentStateManager.activityCreated (FragmentStateManager.java:346)
  at androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1188)
  at androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1356)
  at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState (FragmentManager.java:1434)
  at androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1497)
  at androidx.fragment.app.BackStackRecord.executeOps (BackStackRecord.java:447)
  at androidx.fragment.app.FragmentManager.executeOps (FragmentManager.java:2169)
  at androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:1992)
  at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:1947)
  at androidx.fragment.app.FragmentManager.execPendingActions (FragmentManager.java:1849)
  at androidx.fragment.app.FragmentManager.dispatchStateChange (FragmentManager.java:2629)
  at androidx.fragment.app.FragmentManager.dispatchActivityCreated (FragmentManager.java:2577)
  at androidx.fragment.app.FragmentController.dispatchActivityCreated (FragmentController.java:247)
  at androidx.fragment.app.FragmentActivity.onStart (FragmentActivity.java:541)
  at com.plaid.internal.od0.onStart (SourceFile:1)
  at android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1391)
  at android.app.Activity.performStart (Activity.java:7224)
  at android.app.ActivityThread.handleStartActivity (ActivityThread.java:2971)
  at android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:180)
  at android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:165)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:142)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:70)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1839)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6714)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:503)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:911)
```

**Comment by mking-keeper** [comment]
I'm also running into this issue with `Samsung Galaxy J7 Star Android 9 (SDK 28)`

I'm using plaid-link-android 3.0.1

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3139)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3282)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1970)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7156)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:975)
Caused by: kotlin.UninitializedPropertyAccessException: 
  at com.plaid.link.internal.BasePlaid$Companion.getINSTANCE (BasePlaid.java:1)
  at com.plaid.internal.a.a (a.java:117)
  at com.plaid.internal.link.LinkWebViewActivity.onCreate (LinkWebViewActivity.java:2)
  at android.app.Activity.performCreate (Activity.java:7340)
  at android.app.Activity.performCreate (Activity.java:7331)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1275)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3119)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3282)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1970)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7156)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:975)

```

**Comment by amytang0** [comment]
Hey sorry for the late response, we found the root cause of this issue occurred with low-memory devices. We've fixed this issue for DNKA mode + 0 background processes in `3.1.1`. 
Please let us know if it still repros!

**Comment by JeroenMols** [comment]
Hi all,

Has any of you still seen this crash on `3.1.1` or higher?

We're fully aware that it's very hard to confirm whether or not an occasionally occurring crash is resolved.
But we prefer not to close issues, unless we've gotten some form of confirmation.

Thank you,
Jeroen

**Comment by mking-keeper** [comment]
I still see this issue with `3.2.0`.

Here is an example stack trace I saw in the Play Store console (from November 26):

```
kotlin.UninitializedPropertyAccessException: 
  at com.plaid.link.internal.BasePlaid$Companion.getINSTANCE (BasePlaid.java:1)
  at com.plaid.internal.jg0.a (jg0.java:46)
  at com.plaid.internal.ve0.onActivityCreated (ve0.java:5)
  at androidx.fragment.app.Fragment.performActivityCreated (Fragment.java:2718)
  at androidx.fragment.app.FragmentStateManager.activityCreated (FragmentStateManager.java:346)
  at androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1200)
  at androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1368)
  at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState (FragmentManager.java:1446)
  at androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1509)
  at androidx.fragment.app.FragmentManager.dispatchStateChange (FragmentManager.java:2637)
  at androidx.fragment.app.FragmentManager.dispatchActivityCreated (FragmentManager.java:2589)
  at androidx.fragment.app.FragmentController.dispatchActivityCreated (FragmentController.java:247)
  at androidx.fragment.app.FragmentActivity.onStart (FragmentActivity.java:541)
  at com.plaid.internal.xe0.onStart (xe0.java:1)
  at android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1435)
  at android.app.Activity.performStart (Activity.java:8024)
  at android.app.ActivityThread.handleStartActivity (ActivityThread.java:3475)
  at android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:221)
  at android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:201)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:173)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2066)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:223)
  at android.app.ActivityThread.main (ActivityThread.java:7656)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:592)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:947)
```

So far, I've seen this error on two devices:
- Google Pixel 4XL, Android 11 (SDK 30) 
- LGE Stylo 6, Android 10 (SDK 29)

Let me know if you need any more details.

**Comment by JeroenMols** [comment]
Thanks for getting back to us with this info @mking-keeper, we'll keep on investigating and get back to you!

**Comment by zsweigart** [comment]
Hi @amit-affirm and @mking-keeper we have uncovered the cause of the issue and will be putting it in our next release on December 15th.

**Comment by amistash** [comment]
We are on 3.1.0 and we are also getting several crashes per day with this exception:
Fatal Exception: kotlin.UninitializedPropertyAccessException: lateinit property INSTANCE has not been initialized
       at com.plaid.link.internal.BasePlaid$Companion.getINSTANCE(BasePlaid.java:1)
       at com.plaid.internal.link.LinkDependencyFragment.a(LinkDependencyFragment.java:46)

**Comment by amytang0** [comment]
Hi, can you upgrade to the latest 3.2.1?

**Comment by amistash** [comment]
> Hi, can you upgrade to the latest 3.2.1?

So @amytang0 we don't need to wait for the Dec 15 fix?

**Comment by amytang0** [comment]
We bumped up the fix to this release. Sorry for the confusion!

**Comment by amytang0** [comment]
Closing this issue, please re-open if upgrading to 3.2.1 does not fix the problem. Thanks for reporting!
