### ISSUE TITLE
Plaid link with captcha not working in android devices

### ISSUE THREAD

**Issue by iamjosephmj** [plaid/plaid-link-android#192]
# The problem

I am not able to link bank that involves captcha.
This looks like a UI issue in the link screens. Please find a fix for this ASAP.

# Environment:
Android OS Version : 9,10,11                                 
All android devices tested had this issue:
One plus 7pro, pixel 4a, samsung S20, samsung S21 ultra.

# Steps to Reproduce

Do a simple plaid link that involves captcha.

# Expected Result
User should be able to proceed. And click next button to complete the SDK action. 

# Screenshots
https://user-images.githubusercontent.com/18631114/134002248-bf0a984c-6b6d-4562-9ec9-0ecfd38ea46c.mp4

**Comment by iamjosephmj** [comment]
I am using Plaid-Link version 3.5.1

**Comment by amistash** [comment]
We are also seeing this issue.

**Comment by amytang0** [comment]
Hi we have launched a fully native experience in 3.6.0 that should solve this problem. If you would like to opt-in, please send me your `client_id`'s. Thank you!

**Comment by iamjosephmj** [comment]
@amytang0 this issue is still happening in 3.6.0

We were locally able to reproduce the issue:

https://user-images.githubusercontent.com/18631114/134507898-8bc90be5-07c2-4208-93a8-ff8490e428dd.mp4

**Comment by amytang0** [comment]
Yes you will need to provide your client_id in order to opt into the native
experience

**Comment by amytang0** [comment]
Sounds good!

**Comment by iamjosephmj** [comment]
@amytang0 I had updated "client_id" here -> https://dashboard.plaid.com/support/case/339044.
please contact your support team for the details.

**Comment by iamjosephmj** [comment]
@amytang0 please let me know if you need anything more regarding the link SDK from my side.

**Comment by amytang0** [comment]
Perfect, I've enabled you for sandbox and development server. 
KP: Dark mode is wonky, this will be fixed in the next release

**Comment by iamjosephmj** [comment]
@amytang0 looks good in sandbox and development. I will update the support team about enabling the same in production after QA.

Thankyou so much @amytang0 🙌

Closing this ticket..
