### ISSUE TITLE
Fatal exception: There is no encrypted key stored for encryption or decryption

### ISSUE THREAD

**Issue by shaurya947** [plaid/plaid-link-android#27]
We're using v0.3.1. We briefly upgraded to v0.3.3 but due to #18 reverted back to v0.3.1. It has worked mostly fine when testing in-house, however, a customer experienced the following crash (reported by Crashlytics):

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.cover.android/com.plaid.link.LinkActivity}: java.lang.IllegalStateException: There is no encrypted key stored for encryption or decryption
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3949)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3981)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:205)
       at android.app.ActivityThread.main(ActivityThread.java:6993)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
```

```
Caused by java.lang.IllegalStateException: There is no encrypted key stored for encryption or decryption
       at com.plaid.storage.PlaidKeystore.getSecretKey(PlaidKeystore.kt:283)
       at com.plaid.storage.PlaidKeystore.encrypt$storage_release(PlaidKeystore.kt:95)
       at com.plaid.storage.PlaidSecureStorage.saveData(PlaidSecureStorage.kt:74)
       at com.plaid.analytics.PlaidAnalyticsImpl.loadIdentity(PlaidAnalyticsImpl.kt:158)
       at com.plaid.analytics.PlaidAnalyticsImpl.getUserId(PlaidAnalyticsImpl.kt:45)
       at com.plaid.analytics.PlaidAnalyticsImpl.track(PlaidAnalyticsImpl.kt:90)
       at com.plaid.analytics.PlaidAnalyticsImpl.track(PlaidAnalyticsImpl.kt:81)
       at com.plaid.link.LinkActivity.onResume(LinkActivity.kt:93)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
       at android.app.Activity.performResume(Activity.java:7325)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3941)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3981)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:205)
       at android.app.ActivityThread.main(ActivityThread.java:6993)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
```

Wondering if anyone is having similar issues or if the maintainers can see a probable cause.

**Comment by shaurya947** [comment]
Another (seemingly related?) crash reported by Crashlytics:

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.cover.android/com.plaid.link.LinkActivity}: android.security.keystore.KeyNotYetValidException: Key not yet valid
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3706)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3746)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2941)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1627)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:175)
       at android.app.ActivityThread.main(ActivityThread.java:6724)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
```

```
Caused by android.security.keystore.KeyNotYetValidException: Key not yet valid
       at android.security.KeyStore.getInvalidKeyException(KeyStore.java:728)
       at android.security.KeyStore.getInvalidKeyException(KeyStore.java:794)
       at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
       at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
       at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265)
       at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:109)
       at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2668)
       at javax.crypto.Cipher.tryCombinations(Cipher.java:2561)
       at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2480)
       at javax.crypto.Cipher.chooseProvider(Cipher.java:567)
       at javax.crypto.Cipher.init(Cipher.java:831)
       at javax.crypto.Cipher.init(Cipher.java:772)
       at com.plaid.storage.PlaidKeystore.rsaDecrypt(PlaidKeystore.kt:249)
       at com.plaid.storage.PlaidKeystore.getSecretKey(PlaidKeystore.kt:289)
       at com.plaid.storage.PlaidKeystore.encrypt$storage_release(PlaidKeystore.kt:95)
       at com.plaid.storage.PlaidSecureStorage.saveData(PlaidSecureStorage.kt:74)
       at com.plaid.analytics.PlaidAnalyticsImpl.loadIdentity(PlaidAnalyticsImpl.kt:158)
       at com.plaid.analytics.PlaidAnalyticsImpl.getUserId(PlaidAnalyticsImpl.kt:45)
       at com.plaid.analytics.PlaidAnalyticsImpl.track(PlaidAnalyticsImpl.kt:90)
       at com.plaid.analytics.PlaidAnalyticsImpl.track(PlaidAnalyticsImpl.kt:81)
       at com.plaid.link.LinkActivity.onResume(LinkActivity.kt:93)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1356)
       at android.app.Activity.performResume(Activity.java:7136)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3681)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3746)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2941)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1627)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:175)
       at android.app.ActivityThread.main(ActivityThread.java:6724)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
```

**Comment by zsweigart** [comment]
Hi @shaurya947 thanks for the heads up, this should be fixed in the latest version 0.3.5 which also fixes https://github.com/plaid/plaid-link-android/issues/26

**Comment by shaurya947** [comment]
Thanks for the update @zsweigart . I will update to 0.3.5 in our next release and if we don't see more reports of this crash, I'll close the issue.

**Comment by shaurya947** [comment]
@zsweigart our latest release with 0.3.5 has been out for a while and this crash still seems to be happening. It actually happened for a single user using a galaxy A20 several times and Firebase now says it's a stability issue :(

**Comment by zsweigart** [comment]
We have updated our internal encryption library to Tink in the latest 1.0.0 release https://github.com/google/tink

**Comment by shaurya947** [comment]
Gotcha. Will update to 1.0.0 in our next release and monitor (and close if crash doesn't happen anymore).

**Comment by JeroenMols** [comment]
HI @shaurya947, just wanted to check in to see if you are still seeing these crashes?
That would enable us to either close this ticket or look for alternative solutions.
