### ISSUE TITLE
NoSuchMethodError in SDK 1.2.0 for LinkEvent

### ISSUE THREAD

**Issue by mictab** [plaid/plaid-link-android#44]
Hi!

After updating to SDK 1.2.0 following the fixes due to https://github.com/plaid/plaid-link-android/issues/43 we are having new issues. We are getting runtime exceptions when accessing the getters on LinkEvent.

Example exception:

`java.lang.NoSuchMethodError: No virtual method getEventName()Ljava/lang/String; in class Lcom/plaid/linkbase/models/configuration/LinkEvent; or its super classes (declaration of 'com.plaid.linkbase.models.configuration.LinkEvent'`

Example code:

```kotlin
override fun onLinkEvent(linkEvent: LinkEvent) {
    val eventName = linkEvent.eventName
    val metadata = linkEvent.metadata
    // ...
}
```

Both of these accessors fail at runtime. The crash happens as soon as we open Link and the loading is completed.

We are running this with minify disabled. Ideas?

**Comment by JeroenMols** [comment]
Thanks for reporting, I'm having a look at your issue now

**Comment by zsweigart** [comment]
We have a solution, and we'll be releasing a patch tomorrow.

**Comment by zsweigart** [comment]
We just released version 1.2.1 with the fix

**Comment by ar-abdulazeez** [comment]
Could you please share the plaid proguard config? The classes that I need to keep. I am still seeing this issue with the plaid 1.4.1

**Comment by mictab** [comment]
@ar-abdulazeez We're using the rules below since the tip in https://github.com/plaid/plaid-link-android/issues/15#issuecomment-566760534 didn't work for us.

```
-keep class com.plaid.** { *; }
-dontwarn com.plaid.**
```

**Comment by ar-abdulazeez** [comment]
Thanks @mictab ..that worked for me as well
